```{r setup}
library(glptools)
library(glpdata)
glp_load_packages(graphs = T)

showtext_auto()
font_add("Museo Sans", "MuseoSans_300.otf")
font_add("Museo Sans 300 Italic", "MuseoSans_300_Italic.otf")

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

source("helpers/graph_functions.R")
source("helpers/load_graph_specs.R")
```

```{r}
get_y_lims <- function(df, var, rm, rm_sex, rm_race, xmin, xmax, order, 
                        sex_pctiles, race_pctiles, units = "Percent",
                        categories = c("total", "sex", "race")){
  
  # Trendline
  df_single <- df %>% trend_data(var, rm, xmin, xmax)
  df_processed <- df_single

  # Max-min
  if(df_type(df) %in% c("FIPS", "MSA")){
    df_maxmin <- df %>%
      trend_data_maxmin(var, rm, xmin, xmax, order) %>%
      filter(variable %in% c("best", "worst")) %>%
      mutate(category = "total")

    df_processed %<>% bind_rows(df_maxmin)
  }

  # Sex
  if("sex" %in% categories){
    df_sex <- df %>% trend_data(var, rm_sex, xmin, xmax, cat = "sex", pctiles = sex_pctiles)
    df_processed %<>% bind_rows(df_sex)
  }

  # Race
  if("race" %in% categories){
    df_race <- df %>% trend_data(var, rm_race, xmin, xmax, cat = "race", pctiles = race_pctiles)
    df_processed %<>% bind_rows(df_race)
  }

  # FRL
  if("frl"  %in% categories){
    df_frl <- df %>% trend_data(var, rm, xmin, xmax, cat = "frl_status", pctiles = F)
    df_processed %<>% bind_rows(df_frl)
  }

  # Then use the min and max to determine y axis limits for trendline graphs.
  midpoint <- (max(df_processed[[var]], na.rm = TRUE) +
                 min(df_processed[[var]], na.rm = TRUE))/2

  border_space <- abs(.1 * midpoint)

  ylims <- c(min(df_processed[[var]], na.rm = TRUE) - border_space,
             max(df_processed[[var]], na.rm = TRUE) + border_space)

  if (units == "Percent" & ylims[2] > 100) ylims[2] <- 100

  glptools:::make_list(ylims, df_processed)
}

rm = 1
xmin = 2000
xmax = 2019
order = "descending"
rm_sex = 3
sex_pctiles = F
rm_race = 3
race_pctiles = T

t=get_y_lims(filter(natality_county, var_type == "percent"), "underweight_births", 1, 3, 3, 2003, 2019, "ascending", F, T)

t2=t$df_processed

```


```{r underweight_births}
path <- "output_images/health/underweight_births/underweight_births_"
this_title <- "Underweight Births"
this_subtitle <- "Age-adjusted"
this_caption <- "Source: Greater Louisville Project
   GLP analysis of CDC Wonder Natality data"



png(path %p% "ranking.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
ranking(
  filter(natality_county, var_type == "percent"),
  underweight_births,
  plot_title = this_title %p% ", 2019",
  subtitle_text = this_subtitle,
  order = "Ascending",
  caption_text = this_caption)
dev.off()


png(path %p% "trend.png", 
    3000, 2400, res = 200, bg = "transparent", type = "cairo")
trend(
  filter(natality_county, var_type == "percent"),
  underweight_births,
  plot_title = this_title,
  subtitle_text =  this_subtitle,
  rollmean = 3,
  ylimits = c(5, 17),
  caption_text = this_caption)
dev.off()

png(path %p% "maxmin.png", 
    3000, 2400, res = 200, bg = "transparent", type = "cairo")
trend_maxmin(
  filter(natality_county, var_type == "percent"),
  underweight_births,
  xmin = 2003,
  rollmean = 3,
  order = "ascending",
  ylimits = c(5, 17),
  plot_title = this_title,
  subtitle_text = this_subtitle,
  caption_text = this_caption)
dev.off()

png("output_images/health/underweight_births/underweight_births_change.png", 
    3000, 2400, res = 200, bg = "transparent", type = "cairo")
trend_maxmin(
  filter(natality_county, var_type == "percent"),
  underweight_births,
  zero_start = T,
  rollmean = 3,
  order = "ascending",
  y_title = "Percentage points change",
  plot_title = this_title,
  subtitle_text =  this_subtitle,
  caption_text = this_caption)
dev.off()



png("output_images/health/underweight_births/underweight_births_sex.png", 
    3000, 2400, res = 200, bg = "transparent", type = "cairo")
trend(
  filter(natality_county, var_type == "percent"),
  underweight_births,
  cat = "sex",
  plot_title = this_title,
  subtitle_text = this_subtitle,
  rollmean = 3,
  ylimits = c(5, 17),
  pctiles = FALSE,
  caption_text = this_caption)
dev.off()


png("output_images/health/underweight_births/underweight_births_race.png", 
    3000, 2400, res = 200, bg = "transparent", type = "cairo")
trend(
  filter(natality_county, var_type == "percent"),
  underweight_births,
  cat = "race",
  plot_title = this_title,
  subtitle_text =  this_subtitle,
  rollmean = 3,
  ylimits = c(5, 17),
  caption_text = this_caption)
dev.off()





```

```{r social_associations}
create_images(column = "variable", 
              value = c("social_associations"),
              df = glpdata:::social_associations,
              upload_graphs = T,
              upload_data   = F)
```

```{r mammography_screening}
path <- "output_images/health/mammography_screening/mammography_screening_"
this_title <- "Mammography Screenings"
this_title_trend_graphs <- "Mammography Screenings Among Medicare Enrollees"
this_caption <- "\nSource: Greater Louisville Project
    Data from the CMS Mapping Medicare Disparities tool, 2020"
this_caption_trend_graphs <- "\nSource: Greater Louisville Project
    Data from the CMS Mapping Medicare Disparities tool
    Only Medicare enrollees between the ages of 65 and 74 are included in this analysis"

png(path %p% "ranking.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::ranking(
  mammography_county,
  mammography_screening,
  year = 2020,
  sex = "total",
  race = "total",
  peers = "Current",
  order = "Descending",
  y_title = "Percent of Medicare enrollees (65-74) who are screened yearly",
  plot_title = this_title %p% ", 2020",
  subtitle_text = "Among Medicare enrollees",
  caption_text = this_caption,
  bar_label = TRUE,
  sigfig = 3,
  accuracy = 1,
  alternate_text = NULL,
  ranking_colors = TRUE)
dev.off()


png(path %p% "trend.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  mammography_county, 
  mammography_screening, 
  rollmean = 3,
  plot_title = this_title_trend_graphs, 
  caption_text = this_caption_trend_graphs,
  y_title = "Percent")
dev.off()


if(2020 %in% mammography_county$year) warning("Undo the min_city specification for the new year of data!")

png(path %p% "maxmin.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
trend_maxmin(
  mammography_county,
  mammography_screening,
  zero_start = T,
  rollmean = 3,
  y_title = "Percentage points change",
  min_city = "Greensboro", # REMOVE WITH 2020 DATA
  plot_title = this_title_trend_graphs,
  caption_text = this_caption_trend_graphs)
dev.off()


png(path %p% "race.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  mammography_county, 
  mammography_screening,
  cat='race',
  include_hispanic = T,
  pctiles = F,
  rollmean = 3,
  plot_title = this_title, 
  caption_text = this_caption_trend_graphs,
  y_title = "Percent")
dev.off()


```

```{r flu_vaccines}
path <- "output_images/health/flu_vaccines/flu_vaccines_"
this_title <- "Flu Vaccinations"
this_title_trend_graphs <- "Flu Vaccinations Among Medicare Enrollees"
this_caption <- "\nSource: Greater Louisville Project
    Data from the CMS Mapping Medicare Disparities tool, 2020"
this_caption_trend_graphs <- "\nSource: Greater Louisville Project
    Data from the CMS Mapping Medicare Disparities tool"

png(path %p% "ranking.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::ranking(
  flu_county,
  flu_shot,
  year = 2020,
  sex = "total",
  race = "total",
  peers = "Current",
  order = "Descending",
  y_title = "Percent reimbursed for a flu vaccine",
  plot_title = this_title %p% ", 2020",
  subtitle_text = "Among Medicare enrollees",
  caption_text = this_caption,
  bar_label = TRUE,
  sigfig = 3,
  accuracy = 1,
  alternate_text = NULL,
  ranking_colors = TRUE)
dev.off()


png(path %p% "trend.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  flu_county, 
  flu_shot, 
  rollmean = 3,
  plot_title = this_title_trend_graphs, 
  caption_text = this_caption_trend_graphs,
  y_title = "Percent")
dev.off()


png(path %p% "maxmin.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend_maxmin(
  flu_county,
  flu_shot,
  zero_start = T,
  rollmean = 3,
  y_title = "Percentage points change",
  plot_title = this_title_trend_graphs,
  caption_text = "\nSource: Greater Louisville Project
    Data from the CMS Mapping Medicare Disparities tool")
dev.off()


png(path %p% "race.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
trend(
  flu_county, 
  flu_shot,
  cat='race',
  pctiles = F,
  peers = "none",
  rollmean = 3,
  plot_title = this_title_trend_graphs, 
  caption_text = this_caption_trend_graphs,
  y_title = "Percent")
dev.off()


png(path %p% "sex.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  flu_county, 
  flu_shot,
  cat='sex',
  pctiles = F,
  rollmean = 3,
  plot_title = this_title_trend_graphs, 
  caption_text = this_caption_trend_graphs,
  y_title = "Percent")
dev.off()

```

```{r diabetes_prevalence}
path <- "output_images/health/diabetes_prevalence/diabetes_prevalence_"
this_title <- "Diabetes Prevalence"
this_title_trend_graphs <- "Diabetes Prevalence Among Adults 20 and Older"
this_caption <- "\nSource: Greater Louisville Project
    Data from the CDC's U.S. Diabetes Surveillance System, 2019"
this_caption_trend_graphs <- "\nSource: Greater Louisville Project
    Data from the CDC's U.S. Diabetes Surveillance System"

png(path %p% "ranking.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::ranking(
  diabetes_prevalence_county,
  diabetes_prevalence,
  year = 2019,
  sex = "total",
  race = "total",
  peers = "Current",
  order = "Ascending",
  y_title = "Percent diagnosed with diabetes",
  plot_title = this_title %p% ", 2019",
  subtitle_text = "Among adults 20 and older",
  caption_text = this_caption,
  bar_label = TRUE,
  sigfig = 3,
  accuracy = 0.1,
  alternate_text = NULL,
  ranking_colors = TRUE)
dev.off()


png(path %p% "trend.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  diabetes_prevalence_county,
  diabetes_prevalence, 
  rollmean = 3,
  plot_title = this_title_trend_graphs, 
  caption_text = this_caption_trend_graphs,
  y_title = "Percent")
dev.off()


png(path %p% "maxmin.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend_maxmin(
    diabetes_prevalence_county,
    diabetes_prevalence, 
    min_city = 'Charlotte', #Tie between Charlotte and Cincinnati for the best perfromer; choose Charlotte
    zero_start = T,
    rollmean = 3,
    order='Ascending',
    y_title = "Percentage points change",
    plot_title = this_title_trend_graphs,
    caption_text = this_caption_trend_graphs)
dev.off()


png(path %p% "sex.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  diabetes_prevalence_county, 
  diabetes_prevalence,
  cat='sex',
  pctiles = F,
  rollmean = 3,
  plot_title = this_title_trend_graphs, 
  caption_text = this_caption_trend_graphs,
  y_title = "Percent")
dev.off()

```

```{r insurance}
path <- "output_images/health/insurance/insurance_"
this_title <- "Uninsured"
this_caption <- "\nSource: Greater Louisville Project
    Data from the U.S. Census Bureau's American Community Survey (ACS), 2019"
this_caption_trend_graphs <- "\nSource: Greater Louisville Project
    Data from the U.S. Census Bureau's American Community Survey (ACS)"

png(path %p% "ranking.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::ranking(
  uninsured_county,
  uninsured,
  year = 2019,
  sex = "total",
  race = "total",
  peers = "Current",
  order = "Ascending",
  y_title = "Percent of residents not covered by health insurance",
  plot_title = this_title %p% ", 2019",
  caption_text = this_caption,
  bar_label = TRUE,
  sigfig = 3,
  accuracy = 0.1,
  alternate_text = NULL,
  ranking_colors = TRUE)
dev.off()


png(path %p% "trend.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  uninsured_county,
  uninsured, 
  rollmean = 3,
  plot_title = this_title,
  caption_text = this_caption_trend_graphs,
  y_title = "Percent")
dev.off()


png(path %p% "maxmin.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend_maxmin(
  uninsured_county,
  uninsured,
  zero_start = T,
  order='Ascending',
  rollmean = 3,
  y_title = "Percentage points change",
  plot_title = this_title,
  caption_text = this_caption_trend_graphs)
dev.off()


png(path %p% "sex.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  uninsured_county,
  uninsured,
  cat='sex',
  pctiles = F,
  rollmean = 3,
  plot_title = this_title, 
  caption_text = this_caption_trend_graphs,
  y_title = "Percent")
dev.off()


png(path %p% "race.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  uninsured_county,
  uninsured,
  cat='race',
  include_hispanic = T,
  pctiles = F,
  rollmean = 3,
  plot_title = this_title, 
  caption_text = this_caption_trend_graphs,
  y_title = "Percent")
dev.off()

```

```{r teen_births}
path <- "output_images/health/teen_births/teen_births_"
this_title <- "Teen Births"
subtitle <- "Among women between the ages of 15 and 19"
this_title_trend_graphs = "Teen Births (Ages 15—19)"
this_caption <- "\nSource: Greater Louisville Project
    Data from the CDC's Wonder Natality tool and the U.S. Census Bureau's American Community Survey (ACS), 2019"
this_caption_trend_graphs <- "\nSource: Greater Louisville Project
    Data from the CDC's Wonder Natality tool and the U.S. Census Bureau's American Community Survey (ACS)"

png(path %p% "ranking.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::ranking(
  teen_births_county,
  teen_births_per_1000,
  year = 2019,
  race = "total",
  sex = "female",
  peers = "Current",
  order = "Ascending",
  y_title = "Per 1,000 women",
  plot_title = this_title %p% ", 2019",
  subtitle_text = subtitle,
  caption_text = this_caption,
  bar_label = TRUE,
  sigfig = 3,
  accuracy = 0.1,
  alternate_text = NULL,
  ranking_colors = TRUE)
dev.off()

#For trend graph, need a dataframe without the sex column
teen_births_county_trend <- teen_births_county %>%
  select(-sex)

png(path %p% "trend.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  teen_births_county_trend,
  teen_births_per_1000,
  rollmean = 3,
  plot_title = this_title_trend_graphs,
  caption_text = this_caption_trend_graphs,
  y_title = "Teen births per 1,000 women")
dev.off()


png(path %p% "maxmin.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend_maxmin(
  teen_births_county_trend,
  teen_births_per_1000,
  zero_start = T,
  rollmean = 3,
  order='Ascending',
  y_title = "Change in teen births (per 1,000 women)",
  plot_title = this_title_trend_graphs,
  caption_text = this_caption_trend_graphs)
dev.off()


png(path %p% "race.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  teen_births_county_trend,
  teen_births_per_1000,
  cat='race',
  include_hispanic = T,
  xmin = 2012, #Starting at 2012 because of missing Hispanic data
  pctiles = F,
  rollmean = 3,
  plot_title = this_title_trend_graphs, 
  caption_text = this_caption_trend_graphs,
  y_title = "Teen births per 1,000 women")
dev.off()

```

```{r STIs}
path <- "output_images/health/stis/stis_"
this_title <- "Sexually Transmitted Infections"
this_caption <- "\nSource: Greater Louisville Project
    Data from the CDC's National Center for HIV/AIDS, Viral Hepatitis, STD, and TB Prevention (NCHHSTP) Atlas, 2019"
this_caption_trend_graphs <- "\nSource: Greater Louisville Project
    Data from the CDC's National Center for HIV/AIDS, Viral Hepatitis, STD, and TB Prevention (NCHHSTP) Atlas"

png(path %p% "ranking.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::ranking(
  sti_county,
  rate_per_100000,
  year = 2019,
  race = "total",
  sex = "total",
  peers = "Current",
  order = "Ascending",
  y_title = "Newly diagnosed chlamydia cases per 100,000 people",
  plot_title = this_title %p% ", 2019",
  caption_text = this_caption,
  bar_label = TRUE,
  sigfig = 3,
  accuracy = 0.1,
  alternate_text = NULL,
  ranking_colors = TRUE)
dev.off()


png(path %p% "trend.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  sti_county,
  rate_per_100000,
  rollmean = 3,
  plot_title = this_title,
  caption_text = this_caption_trend_graphs,
  y_title = "Newly diagnosed chlamydia cases per 100,000 people")
dev.off()

```

```{r obesity}
path <- "output_images/health/obesity/obesity_"
this_title <- "Adult Obesity"
this_title_trend_graphs <- "Obesity Among Adults 20 and Older"
this_caption <- "\nSource: Greater Louisville Project
    Data from the CDC's U.S. Diabetes Surveillance System, 2019"
this_caption_trend_graphs <- "\nSource: Greater Louisville Project
    Data from the CDC's U.S. Diabetes Surveillance System
Note: Obese adults are defined as those with a BMI of 30 or above."

png(path %p% "ranking.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::ranking(
  obesity_county,
  obesity_percentage,
  year = 2019,
  sex = "total",
  race = "total",
  peers = "Current",
  order = "Ascending",
  y_title = "Percent",
  plot_title = this_title %p% ", 2019",
  subtitle_text = "Adults 20 and older with a BMI of 30 or above",
  caption_text = this_caption,
  bar_label = TRUE,
  sigfig = 3,
  accuracy = 0.1,
  alternate_text = NULL,
  ranking_colors = TRUE)
dev.off()


png(path %p% "trend.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  obesity_county,
  obesity_percentage, 
  rollmean = 3,
  plot_title = this_title_trend_graphs, 
  caption_text = this_caption_trend_graphs,
  y_title = "Percent")
dev.off()


png(path %p% "maxmin.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend_maxmin(
  obesity_county,
  obesity_percentage, 
  zero_start = T,
  rollmean = 3,
  order='Ascending',
  y_title = "Percentage points change",
  plot_title = this_title_trend_graphs,
  caption_text = this_caption_trend_graphs)
dev.off()


png(path %p% "sex.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::trend(
  obesity_county,
  obesity_percentage, 
  cat='sex',
  pctiles = F,
  rollmean = 3,
  plot_title = this_title_trend_graphs, 
  caption_text = this_caption_trend_graphs,
  y_title = "Percent")
dev.off()

```

```{r smoking}
path <- "output_images/health/smoking/smoking_"
this_title <- "Smoking"
this_caption <- "\nSource: Greater Louisville Project
    Data from the CDC's Behavioral Risk Factor Surveillance System (BRFSS), 2019"

png(path %p% "ranking.png", 3000, 2400, res = 200, bg = "transparent", type = "cairo")
glptools::ranking(
  smoking_county,
  smoking_percentage,
  year = 2019,
  sex = "total",
  race = "total",
  peers = "Current",
  order = "Ascending",
  y_title = "Percent",
  plot_title = this_title %p% ", 2019",
  subtitle_text = "Adults who are current smokers",
  caption_text = this_caption,
  bar_label = TRUE,
  sigfig = 3,
  accuracy = 0.1,
  alternate_text = NULL,
  ranking_colors = TRUE)
dev.off()
```
